### ISSUE TITLE
关于数据样本的问题

### ISSUE THREAD

**Issue by Dahuiza** [SeaEagleI/judicial_document_analysis#2]
大佬好！我想问一下前100个数据样本里似乎并没有s21正文字段，想问这个部分应该如何获取呢？

**Comment by SeaEagleI** [comment]
我记得s21好像是后面几个字段拼接起来的，你可以找几个样例研究下。必要的话可以将几个字段拼接合成s21。
我们在爬取前对字段的重复性做了研究，所以为了数据下载下来不太大，不会强行爬取每个字段。

**Comment by Dahuiza** [comment]
谢谢大佬！看了一下，后面几个字段的拼接似乎还缺少文书前面一部分文字，我再研究一下吧。
另外想弱弱的问一下，如果可以的话，大佬之前爬取的数据是否可以共享qwq已经被ban了很多账号了，正处于一筹莫展的状态……
